# Generated by Django 5.2 on 2025-04-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_character_count_document_page_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_hash',
            field=models.CharField(default='jkxkqjqnj', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
