# Generated by Django 5.2 on 2025-04-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='_highlights',
            field=models.JSONField(default=list),
        ),
    ]
